services:
  postgres:
    image: postgres:15
    container_name: next_pizza_db_dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: next_pizza
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  studio:
    image: node:18-alpine
    container_name: next_pizza_studio
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5555:5555"
    command: sh -c "npm ci && npx prisma generate && npx prisma studio --hostname 0.0.0.0"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/next_pizza

volumes:
  postgres_data:
